window.onload = load;

function load() {
	var elements = document.getElementsByTagName('body');
	var body = elements[0];
	
	console.log('current last child' + body.lastChild);
	console.log(body.lastChild);
	console.log(body.lastChild.textContent=='SCRIPT GENERATED BY SERVER! PLEASE REMOVE');
	
	for(var j = body.childNodes.length; j > 0; j--) {
		if(body.childNodes.item(j-1).textContent=='SCRIPT GENERATED BY SERVER! PLEASE REMOVE') {
			for(var i=10; i>0; i--) {
				removeLastChild(body);
			}
			return; // stop the outer loop
		}
	}
}
 
function removeLastChild(body) {
	console.log('removing last child...');
	body.removeChild(body.lastChild);
	console.log('current last child' + body.lastChild);
}




